
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const AdminCompetitions = lazy(() => import("./pages/AdminCompetitions.tsx"));
const AdminDashboard = lazy(() => import("./pages/AdminDashboard.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const CommanderNova = lazy(() => import("./pages/CommanderNova.tsx"));
const PlayerInsights = lazy(() => import("./pages/PlayerInsights.tsx"));
const PresentMode = lazy(() => import("./pages/PresentMode.tsx"));
const TeamInsights = lazy(() => import("./pages/TeamInsights.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/admin-competitions", element: <UserGuard><AdminCompetitions /></UserGuard>},
	{ path: "/admincompetitions", element: <UserGuard><AdminCompetitions /></UserGuard>},
	{ path: "/admin-dashboard", element: <UserGuard><AdminDashboard /></UserGuard>},
	{ path: "/admindashboard", element: <UserGuard><AdminDashboard /></UserGuard>},
	{ path: "/", element: <App />},
	{ path: "/commander-nova", element: <CommanderNova />},
	{ path: "/commandernova", element: <CommanderNova />},
	{ path: "/player-insights", element: <PlayerInsights />},
	{ path: "/playerinsights", element: <PlayerInsights />},
	{ path: "/present-mode", element: <PresentMode />},
	{ path: "/presentmode", element: <PresentMode />},
	{ path: "/team-insights", element: <TeamInsights />},
	{ path: "/teaminsights", element: <TeamInsights />},

];
